baseURL = "https://innotec.techupi.id/"
languageCode = "en"
title = "InnoTEC Research Group"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
  tagline = "Innovation in Telecommunication, Electronics, and Computer"
  description = "InnoTEC (Innovation in Telecommunication, Electronics, and Computer) is a research group at Universitas Pendidikan Indonesia."
  affiliation = "Universitas Pendidikan Indonesia"
  address = "Jl. Setiabudi 229, Sukasari, Bandung 40154, Indonesia"

[menus]
  [[menus.main]]
    name = "Members"
    pageRef = "/members"
    weight = 10
  [[menus.main]]
    name = "Research"
    pageRef = "/projects"
    weight = 20
  [[menus.main]]
    name = "Publications"
    pageRef = "/publications"
    weight = 30
  [[menus.main]]
    name = "News"
    pageRef = "/news"
    weight = 40

[markup.goldmark.renderer]
  unsafe = false
